import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface GenerateRequest {
  resourceId: string;
  title: string;
  tagline: string;
  category: string;
  description: string;
  regenerate?: boolean;
}

function getCategoryTheme(category: string): { color: string; accent: string; mood: string } {
  switch (category) {
    case 'negotiation':
      return { color: 'deep navy blue', accent: 'cyan', mood: 'strategic and empowering' };
    case 'claims':
      return { color: 'dark slate', accent: 'orange', mood: 'urgent and protective' };
    case 'education':
      return { color: 'charcoal', accent: 'gold', mood: 'revealing and enlightening' };
    case 'comparison':
      return { color: 'dark gray', accent: 'green', mood: 'analytical and clear' };
    default:
      return { color: 'dark blue', accent: 'cyan', mood: 'professional' };
  }
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { resourceId, title, tagline, category, description, regenerate } = await req.json() as GenerateRequest;
    
    console.log(`Generating book cover for: ${title} (regenerate: ${regenerate})`);

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Check if cover already exists (unless regenerating)
    if (!regenerate) {
      const { data: existing } = await supabase
        .from('generated_book_covers')
        .select('image_url')
        .eq('resource_id', resourceId)
        .single();

      if (existing?.image_url) {
        console.log('Cover already exists, returning cached URL');
        return new Response(JSON.stringify({ 
          imageUrl: existing.image_url,
          cached: true 
        }), {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
    }

    const theme = getCategoryTheme(category);
    
    const prompt = `Create a professional 3D book cover mockup with a clean white or light gray background (NOT transparent).

Book Details:
- Title: "${title}"
- Subtitle: "${tagline}"
- Category: ${category}

Design Requirements:
- 3D perspective view, angled approximately 15 degrees from front-right
- Visible spine on the left side with thickness suggesting 15-20 pages
- Cover color: ${theme.color} with ${theme.accent} accent elements
- Clean, bold typography - title must be highly legible
- ${theme.mood} aesthetic
- Professional business/home improvement style
- Subtle shadow beneath the book for depth
- Photorealistic lighting with soft highlights
- Modern minimalist design
- NO text other than the title and subtitle
- Dimensions: portrait orientation, approximately 4:5 aspect ratio

The book should look like a real physical book you'd find at a professional conference or real estate office.`;

    console.log('Calling Lovable AI for image generation...');

    const aiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image-preview",
        messages: [{ role: "user", content: prompt }],
        modalities: ["image", "text"],
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('AI Gateway error:', aiResponse.status, errorText);
      
      if (aiResponse.status === 429) {
        return new Response(JSON.stringify({ error: "Rate limit exceeded. Please try again later." }), {
          status: 429,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
      if (aiResponse.status === 402) {
        return new Response(JSON.stringify({ error: "AI credits exhausted. Please add funds." }), {
          status: 402,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
      throw new Error(`AI generation failed: ${aiResponse.status}`);
    }

    const aiData = await aiResponse.json();
    console.log('AI response received');

    const imageData = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    if (!imageData) {
      console.error('No image in AI response:', JSON.stringify(aiData));
      throw new Error("No image generated by AI");
    }

    // Extract base64 data and convert to blob
    const base64Match = imageData.match(/^data:image\/(\w+);base64,(.+)$/);
    if (!base64Match) {
      throw new Error("Invalid image format from AI");
    }

    const imageType = base64Match[1];
    const base64Data = base64Match[2];
    const binaryData = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));

    // Upload to Supabase Storage
    const fileName = `${resourceId}-${Date.now()}.${imageType}`;
    console.log(`Uploading to storage: ${fileName}`);

    const { error: uploadError } = await supabase.storage
      .from('book-covers')
      .upload(fileName, binaryData, {
        contentType: `image/${imageType}`,
        upsert: true,
      });

    if (uploadError) {
      console.error('Storage upload error:', uploadError);
      throw new Error(`Failed to upload image: ${uploadError.message}`);
    }

    // Get public URL
    const { data: { publicUrl } } = supabase.storage
      .from('book-covers')
      .getPublicUrl(fileName);

    console.log(`Image uploaded successfully: ${publicUrl}`);

    // Save to database (upsert for regeneration)
    const { error: dbError } = await supabase
      .from('generated_book_covers')
      .upsert({
        resource_id: resourceId,
        image_url: publicUrl,
        prompt_used: prompt,
      }, {
        onConflict: 'resource_id',
      });

    if (dbError) {
      console.error('Database error:', dbError);
      // Don't fail - the image is still uploaded
    }

    return new Response(JSON.stringify({ 
      imageUrl: publicUrl,
      cached: false 
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error in generate-book-cover:', error);
    return new Response(JSON.stringify({ 
      error: error instanceof Error ? error.message : "Unknown error" 
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
