import { createClient, SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Rate limiting helper
async function checkRateLimit(
  supabase: SupabaseClient,
  identifier: string,
  limit: number,
  windowMs: number
): Promise<boolean> {
  const windowStart = new Date(Date.now() - windowMs).toISOString();
  
  const { count } = await supabase
    .from("rate_limits")
    .select("*", { count: "exact", head: true })
    .eq("identifier", identifier)
    .eq("endpoint", "generate-presentation")
    .gte("created_at", windowStart);

  if ((count ?? 0) >= limit) {
    return false;
  }

  await supabase.from("rate_limits").insert({
    identifier,
    endpoint: "generate-presentation",
  } as Record<string, unknown>);

  return true;
}

// Build prompt based on report type
function buildPrompt(reportType: string, data: Record<string, unknown>): string {
  switch (reportType) {
    case "quote-analysis":
      return buildQuoteAnalysisPrompt(data);
    case "comparison-report":
      return buildComparisonReportPrompt(data);
    default:
      throw new Error(`Unsupported report type: ${reportType}`);
  }
}

function buildQuoteAnalysisPrompt(data: Record<string, unknown>): string {
  const {
    overallScore,
    safetyScore,
    scopeScore,
    priceScore,
    finePrintScore,
    warrantyScore,
    summary,
    warnings,
    missingItems,
    estimatedPrice,
    priceAssessment,
    homeownerName,
    areaName,
  } = data;

  const warningsList = Array.isArray(warnings) ? warnings.join("\n- ") : "None identified";
  const missingList = Array.isArray(missingItems) ? missingItems.join("\n- ") : "None identified";

  return `Create a professional "Homeowner Window Quote Analysis" presentation for ${homeownerName || "the homeowner"}${areaName ? ` regarding their ${areaName} project` : ""}.

## Executive Summary
${summary || "A comprehensive analysis of your window replacement quote."}

## Overall Assessment
- **Overall Score**: ${overallScore || "N/A"}/100
- **Price Assessment**: ${priceAssessment || "Under review"}
- **Estimated Project Cost**: ${estimatedPrice ? `$${estimatedPrice.toLocaleString()}` : "Not specified"}

## Detailed Scores Breakdown
| Category | Score | Status |
|----------|-------|--------|
| Safety & Compliance | ${safetyScore || "N/A"}/100 | ${getScoreStatus(safetyScore as number)} |
| Scope Completeness | ${scopeScore || "N/A"}/100 | ${getScoreStatus(scopeScore as number)} |
| Price Fairness | ${priceScore || "N/A"}/100 | ${getScoreStatus(priceScore as number)} |
| Fine Print Review | ${finePrintScore || "N/A"}/100 | ${getScoreStatus(finePrintScore as number)} |
| Warranty Coverage | ${warrantyScore || "N/A"}/100 | ${getScoreStatus(warrantyScore as number)} |

## Key Warnings to Address
${warningsList ? `- ${warningsList}` : "No critical warnings identified."}

## Missing Items to Request
${missingList ? `- ${missingList}` : "Quote appears complete."}

## Recommended Next Steps
1. Review the warnings above with your contractor
2. Request written clarification on any missing items
3. Compare with at least 2-3 other quotes before making a decision
4. Schedule a follow-up consultation if needed

---
*This analysis was generated by the It's Window Man Quote Scanner tool to help homeowners make informed decisions about their window replacement projects.*`;
}

function buildComparisonReportPrompt(data: Record<string, unknown>): string {
  const { tiers, windowCount, homeownerName, viewMode } = data;

  const tierData = tiers as Array<{
    name: string;
    pricePerWindow: number;
    trueCost10Year: number;
    features: Record<string, unknown>;
  }>;

  const tierRows = tierData
    ?.map((tier) => {
      const upfrontCost = (tier.pricePerWindow || 0) * (windowCount as number || 10);
      return `| ${tier.name} | $${upfrontCost.toLocaleString()} | $${(tier.trueCost10Year || 0).toLocaleString()} |`;
    })
    .join("\n") || "";

  const savings = tierData && tierData.length >= 2 
    ? (tierData[0].trueCost10Year || 0) - (tierData[tierData.length - 1].trueCost10Year || 0)
    : 0;

  return `Create a professional "Window Quality Comparison Guide" presentation for ${homeownerName || "the homeowner"}.

## Project Overview
- **Number of Windows**: ${windowCount || 10}
- **Analysis Mode**: ${viewMode === "longterm" ? "10-Year True Cost" : "Upfront Price"}

## Side-by-Side Comparison

| Window Tier | Upfront Cost | 10-Year True Cost |
|-------------|--------------|-------------------|
${tierRows}

## Potential Savings
By choosing premium windows over budget options, you could save approximately **$${Math.abs(savings).toLocaleString()}** over 10 years through:
- Reduced energy bills (better insulation)
- Lower maintenance costs
- Fewer replacements needed
- Better warranty coverage

## Key Differentiators

### Budget Windows
- Lower upfront cost
- Basic energy efficiency
- Standard warranty (typically 5-10 years)
- May require earlier replacement

### Mid-Range Windows
- Balanced cost-to-value ratio
- Good energy efficiency
- Extended warranty options
- Suitable for most homes

### Premium Windows
- Highest upfront investment
- Superior energy efficiency
- Lifetime warranties available
- Best long-term value

## Recommendation
${savings > 0 
  ? `Based on the 10-year analysis, investing in higher-quality windows could save you $${Math.abs(savings).toLocaleString()} in the long run.`
  : "Consider your budget, home value, and how long you plan to stay in your home when making your decision."}

---
*This comparison was generated by the It's Window Man Comparison Tool to help homeowners understand the true cost of window replacement.*`;
}

function getScoreStatus(score: number | undefined): string {
  if (score === undefined || score === null) return "⚪ Not Rated";
  if (score >= 80) return "🟢 Excellent";
  if (score >= 60) return "🟡 Fair";
  return "🔴 Needs Review";
}

// Poll Gamma API for completion
async function pollForCompletion(
  generationId: string,
  apiKey: string,
  maxWaitMs: number = 60000,
  intervalMs: number = 5000
): Promise<{ status: string; gammaUrl?: string; error?: string }> {
  const startTime = Date.now();
  
  while (Date.now() - startTime < maxWaitMs) {
    const response = await fetch(`https://api.gamma.app/v1/generations/${generationId}`, {
      method: "GET",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Gamma poll error:", errorText);
      throw new Error(`Failed to check generation status: ${response.status}`);
    }

    const result = await response.json();
    console.log("Gamma poll result:", result.status);

    if (result.status === "completed") {
      return { 
        status: "completed", 
        gammaUrl: result.url || result.webUrl || result.gammaUrl 
      };
    }

    if (result.status === "failed" || result.status === "error") {
      return { 
        status: "failed", 
        error: result.error || "Generation failed" 
      };
    }

    // Wait before next poll
    await new Promise((resolve) => setTimeout(resolve, intervalMs));
  }

  return { status: "timeout", error: "Generation timed out after 60 seconds" };
}

Deno.serve(async (req) => {
  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Validate request method
    if (req.method !== "POST") {
      return new Response(
        JSON.stringify({ error: "Method not allowed" }),
        { status: 405, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // ===== RATE LIMIT IDENTIFIER =====
    // Use IP address for rate limiting (allows anonymous access)
    const forwardedFor = req.headers.get("x-forwarded-for");
    const clientIp = forwardedFor?.split(",")[0]?.trim() || "unknown";
    const rateLimitId = `ip:${clientIp}`;
    console.log(`Request from: ${rateLimitId}`);
    
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    // ===== END RATE LIMIT IDENTIFIER =====

    // Parse request body
    const body = await req.json();
    const { reportType, data } = body;

    // Validate required fields
    if (!reportType || typeof reportType !== "string") {
      return new Response(
        JSON.stringify({ error: "reportType is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (!data || typeof data !== "object") {
      return new Response(
        JSON.stringify({ error: "data object is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Initialize Supabase client for rate limiting (with service role)
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Rate limiting: 5 generations per hour per IP
    const allowed = await checkRateLimit(supabase, rateLimitId, 5, 60 * 60 * 1000);
    
    if (!allowed) {
      return new Response(
        JSON.stringify({ error: "Rate limit exceeded. Please try again later." }),
        { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Get Gamma API key
    const gammaApiKey = Deno.env.get("GAMMA_API_KEY");
    if (!gammaApiKey) {
      console.error("GAMMA_API_KEY not configured");
      return new Response(
        JSON.stringify({ error: "Presentation service not configured" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Build prompt based on report type
    let prompt: string;
    try {
      prompt = buildPrompt(reportType, data);
    } catch (err) {
      return new Response(
        JSON.stringify({ error: (err as Error).message }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log(`Generating ${reportType} presentation for ${rateLimitId}...`);

    // Call Gamma API to start generation
    const gammaResponse = await fetch("https://api.gamma.app/v1/generations", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${gammaApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        prompt,
        outputType: "presentation",
      }),
    });

    if (!gammaResponse.ok) {
      const errorText = await gammaResponse.text();
      console.error("Gamma API error:", errorText);
      return new Response(
        JSON.stringify({ error: "Failed to start presentation generation" }),
        { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const gammaResult = await gammaResponse.json();
    const generationId = gammaResult.id || gammaResult.generationId;

    if (!generationId) {
      console.error("No generation ID returned:", gammaResult);
      return new Response(
        JSON.stringify({ error: "Invalid response from presentation service" }),
        { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log(`Generation started with ID: ${generationId}`);

    // Poll for completion
    const pollResult = await pollForCompletion(generationId, gammaApiKey);

    if (pollResult.status === "completed" && pollResult.gammaUrl) {
      console.log(`Generation completed: ${pollResult.gammaUrl}`);
      return new Response(
        JSON.stringify({ 
          success: true, 
          url: pollResult.gammaUrl,
          generationId 
        }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Handle failure or timeout
    console.error(`Generation failed: ${pollResult.error}`);
    return new Response(
      JSON.stringify({ 
        error: pollResult.error || "Failed to generate presentation",
        status: pollResult.status 
      }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );

  } catch (error) {
    console.error("Unexpected error:", error);
    return new Response(
      JSON.stringify({ error: "An unexpected error occurred" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
