import { createClient, SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Rate limiting helper
async function checkRateLimit(
  supabase: SupabaseClient,
  identifier: string,
  limit: number,
  windowMs: number
): Promise<boolean> {
  try {
    const windowStart = new Date(Date.now() - windowMs).toISOString();
    
    const { count, error } = await supabase
      .from("rate_limits")
      .select("*", { count: "exact", head: true })
      .eq("identifier", identifier)
      .eq("endpoint", "generate-presentation")
      .gte("created_at", windowStart);

    if (error) {
      console.error("Rate limit check error:", error);
      // Allow request if rate limit check fails
      return true;
    }

    if ((count ?? 0) >= limit) {
      return false;
    }

    await supabase.from("rate_limits").insert({
      identifier,
      endpoint: "generate-presentation",
    } as Record<string, unknown>);

    return true;
  } catch (err) {
    console.error("Rate limit error:", err);
    return true; // Allow request on error
  }
}

// Build prompt based on report type
function buildPrompt(reportType: string, data: Record<string, unknown>): string {
  switch (reportType) {
    case "quote-analysis":
      return buildQuoteAnalysisPrompt(data);
    case "comparison-report":
      return buildComparisonReportPrompt(data);
    default:
      throw new Error(`Unsupported report type: ${reportType}`);
  }
}

function buildQuoteAnalysisPrompt(data: Record<string, unknown>): string {
  const {
    overallScore,
    safetyScore,
    scopeScore,
    priceScore,
    finePrintScore,
    warrantyScore,
    summary,
    warnings,
    missingItems,
    estimatedPrice,
    priceAssessment,
    homeownerName,
    areaName,
  } = data;

  const warningsList = Array.isArray(warnings) ? warnings.join("\n- ") : "None identified";
  const missingList = Array.isArray(missingItems) ? missingItems.join("\n- ") : "None identified";

  return `Create a professional "Homeowner Window Quote Analysis" presentation for ${homeownerName || "the homeowner"}${areaName ? ` regarding their ${areaName} project` : ""}.

## Executive Summary
${summary || "A comprehensive analysis of your window replacement quote."}

## Overall Assessment
- **Overall Score**: ${overallScore || "N/A"}/100
- **Price Assessment**: ${priceAssessment || "Under review"}
- **Estimated Project Cost**: ${estimatedPrice ? `$${Number(estimatedPrice).toLocaleString()}` : "Not specified"}

## Detailed Scores Breakdown
| Category | Score | Status |
|----------|-------|--------|
| Safety & Compliance | ${safetyScore || "N/A"}/100 | ${getScoreStatus(safetyScore as number)} |
| Scope Completeness | ${scopeScore || "N/A"}/100 | ${getScoreStatus(scopeScore as number)} |
| Price Fairness | ${priceScore || "N/A"}/100 | ${getScoreStatus(priceScore as number)} |
| Fine Print Review | ${finePrintScore || "N/A"}/100 | ${getScoreStatus(finePrintScore as number)} |
| Warranty Coverage | ${warrantyScore || "N/A"}/100 | ${getScoreStatus(warrantyScore as number)} |

## Key Warnings to Address
${warningsList ? `- ${warningsList}` : "No critical warnings identified."}

## Missing Items to Request
${missingList ? `- ${missingList}` : "Quote appears complete."}

## Recommended Next Steps
1. Review the warnings above with your contractor
2. Request written clarification on any missing items
3. Compare with at least 2-3 other quotes before making a decision
4. Schedule a follow-up consultation if needed

---
*This analysis was generated by the It's Window Man Quote Scanner tool to help homeowners make informed decisions about their window replacement projects.*`;
}

function buildComparisonReportPrompt(data: Record<string, unknown>): string {
  const { tiers, windowCount, homeownerName, viewMode } = data;

  const tierData = tiers as Array<{
    name: string;
    pricePerWindow: number;
    trueCost10Year: number;
    features: Record<string, unknown>;
  }>;

  const tierRows = tierData
    ?.map((tier) => {
      const upfrontCost = (tier.pricePerWindow || 0) * (windowCount as number || 10);
      return `| ${tier.name} | $${upfrontCost.toLocaleString()} | $${(tier.trueCost10Year || 0).toLocaleString()} |`;
    })
    .join("\n") || "";

  const savings = tierData && tierData.length >= 2 
    ? (tierData[0].trueCost10Year || 0) - (tierData[tierData.length - 1].trueCost10Year || 0)
    : 0;

  return `Create a professional "Window Quality Comparison Guide" presentation for ${homeownerName || "the homeowner"}.

## Project Overview
- **Number of Windows**: ${windowCount || 10}
- **Analysis Mode**: ${viewMode === "longterm" ? "10-Year True Cost" : "Upfront Price"}

## Side-by-Side Comparison

| Window Tier | Upfront Cost | 10-Year True Cost |
|-------------|--------------|-------------------|
${tierRows}

## Potential Savings
By choosing premium windows over budget options, you could save approximately **$${Math.abs(savings).toLocaleString()}** over 10 years through:
- Reduced energy bills (better insulation)
- Lower maintenance costs
- Fewer replacements needed
- Better warranty coverage

## Key Differentiators

### Budget Windows
- Lower upfront cost
- Basic energy efficiency
- Standard warranty (typically 5-10 years)
- May require earlier replacement

### Mid-Range Windows
- Balanced cost-to-value ratio
- Good energy efficiency
- Extended warranty options
- Suitable for most homes

### Premium Windows
- Highest upfront investment
- Superior energy efficiency
- Lifetime warranties available
- Best long-term value

## Recommendation
${savings > 0 
  ? `Based on the 10-year analysis, investing in higher-quality windows could save you $${Math.abs(savings).toLocaleString()} in the long run.`
  : "Consider your budget, home value, and how long you plan to stay in your home when making your decision."}

---
*This comparison was generated by the It's Window Man Comparison Tool to help homeowners understand the true cost of window replacement.*`;
}

function getScoreStatus(score: number | undefined): string {
  if (score === undefined || score === null) return "⚪ Not Rated";
  if (score >= 80) return "🟢 Excellent";
  if (score >= 60) return "🟡 Fair";
  return "🔴 Needs Review";
}

Deno.serve(async (req) => {
  console.log("[generate-presentation] Request received:", req.method);

  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Validate request method
    if (req.method !== "POST") {
      console.log("[generate-presentation] Method not allowed:", req.method);
      return new Response(
        JSON.stringify({ error: "Method not allowed" }),
        { status: 405, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // ===== CONFIGURATION CHECK =====
    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    const gammaApiKey = Deno.env.get("GAMMA_API_KEY");

    console.log("[generate-presentation] Config check - SUPABASE_URL:", !!supabaseUrl);
    console.log("[generate-presentation] Config check - SERVICE_ROLE_KEY:", !!supabaseKey);
    console.log("[generate-presentation] Config check - GAMMA_API_KEY:", !!gammaApiKey);

    if (!supabaseUrl || !supabaseKey) {
      console.error("[generate-presentation] Missing Supabase configuration");
      return new Response(
        JSON.stringify({ error: "Missing configuration: Supabase credentials not set" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (!gammaApiKey) {
      console.error("[generate-presentation] GAMMA_API_KEY not configured");
      return new Response(
        JSON.stringify({ 
          error: "Presentation service not configured",
          detail: "The GAMMA_API_KEY secret is missing. Please add it in the Supabase dashboard."
        }),
        { status: 503, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // ===== RATE LIMIT IDENTIFIER =====
    const forwardedFor = req.headers.get("x-forwarded-for");
    const clientIp = forwardedFor?.split(",")[0]?.trim() || "unknown";
    const rateLimitId = `ip:${clientIp}`;
    console.log(`[generate-presentation] Request from: ${rateLimitId}`);

    // Parse request body
    let body: { reportType?: string; data?: Record<string, unknown> };
    try {
      body = await req.json();
      console.log("[generate-presentation] Request body parsed, reportType:", body?.reportType);
    } catch (parseError) {
      console.error("[generate-presentation] Failed to parse request body:", parseError);
      return new Response(
        JSON.stringify({ error: "Invalid JSON in request body" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const { reportType, data } = body;

    // Validate required fields
    if (!reportType || typeof reportType !== "string") {
      console.log("[generate-presentation] Missing reportType");
      return new Response(
        JSON.stringify({ error: "reportType is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (!data || typeof data !== "object") {
      console.log("[generate-presentation] Missing data object");
      return new Response(
        JSON.stringify({ error: "data object is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Initialize Supabase client for rate limiting
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Rate limiting: 5 generations per hour per IP
    console.log("[generate-presentation] Checking rate limit...");
    const allowed = await checkRateLimit(supabase, rateLimitId, 5, 60 * 60 * 1000);
    
    if (!allowed) {
      console.log("[generate-presentation] Rate limit exceeded for:", rateLimitId);
      return new Response(
        JSON.stringify({ error: "Rate limit exceeded. Please try again later (max 5 per hour)." }),
        { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Build prompt based on report type
    let prompt: string;
    try {
      prompt = buildPrompt(reportType, data);
      console.log("[generate-presentation] Prompt built successfully, length:", prompt.length);
    } catch (err) {
      console.error("[generate-presentation] Prompt build error:", err);
      return new Response(
        JSON.stringify({ error: (err as Error).message }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log(`[generate-presentation] Calling Gamma API for ${reportType}...`);

    // Gamma API v1.0 - Verified endpoint and parameters
    const gammaEndpoint = "https://public-api.gamma.app/v1.0/generations";
    
    let gammaResponse: Response;
    try {
      const requestBody = {
        inputText: prompt,
        textMode: "generate", // Required: "generate", "condense", or "preserve"
        format: "presentation",
      };
      
      console.log("[generate-presentation] Request body:", JSON.stringify(requestBody).substring(0, 200));
      
      gammaResponse = await fetch(gammaEndpoint, {
        method: "POST",
        headers: {
          "X-API-KEY": gammaApiKey, // Gamma uses X-API-KEY, not Bearer token
          "Content-Type": "application/json",
        },
        body: JSON.stringify(requestBody),
      });
    } catch (fetchError) {
      console.error("[generate-presentation] Gamma API fetch error:", fetchError);
      return new Response(
        JSON.stringify({ 
          error: "Failed to connect to presentation service",
          detail: String(fetchError)
        }),
        { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log("[generate-presentation] Gamma API response status:", gammaResponse.status);

    if (!gammaResponse.ok) {
      const errorText = await gammaResponse.text();
      console.error("[generate-presentation] Gamma API error response:", errorText);
      console.error("[generate-presentation] Gamma API status:", gammaResponse.status);
      
      // Check for specific error types
      if (gammaResponse.status === 401 || gammaResponse.status === 403) {
        return new Response(
          JSON.stringify({ 
            error: "Gamma API authentication failed",
            detail: "The API key may be invalid or expired. Please check the GAMMA_API_KEY secret."
          }),
          { status: 503, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      
      if (gammaResponse.status === 404) {
        return new Response(
          JSON.stringify({ 
            error: "Gamma API endpoint not found",
            detail: "The Gamma API may have changed. Please check for API updates."
          }),
          { status: 503, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      return new Response(
        JSON.stringify({ 
          error: "Presentation generation failed",
          detail: `Gamma API returned ${gammaResponse.status}: ${errorText.substring(0, 200)}`
        }),
        { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    let gammaResult: Record<string, unknown>;
    try {
      gammaResult = await gammaResponse.json();
      console.log("[generate-presentation] Gamma API response:", JSON.stringify(gammaResult).substring(0, 500));
    } catch (jsonError) {
      console.error("[generate-presentation] Failed to parse Gamma response:", jsonError);
      return new Response(
        JSON.stringify({ error: "Invalid response from presentation service" }),
        { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Check for URL in response (Gamma may return URL directly or in various fields)
    const presentationUrl = 
      gammaResult.url || 
      gammaResult.webUrl || 
      gammaResult.gammaUrl || 
      gammaResult.presentationUrl ||
      (gammaResult.data as Record<string, unknown>)?.url;

    if (presentationUrl) {
      console.log(`[generate-presentation] Success! URL: ${presentationUrl}`);
      return new Response(
        JSON.stringify({ 
          success: true, 
          url: presentationUrl
        }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // If no URL, check for generation ID (async generation)
    const generationId = gammaResult.id || gammaResult.generationId;
    if (generationId) {
      console.log(`[generate-presentation] Async generation started: ${generationId}`);
      // For async, return the ID so frontend can poll
      return new Response(
        JSON.stringify({ 
          success: true, 
          status: "pending",
          generationId,
          message: "Presentation is being generated. Please poll for status."
        }),
        { status: 202, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Unexpected response format
    console.error("[generate-presentation] Unexpected response format:", gammaResult);
    return new Response(
      JSON.stringify({ 
        error: "Unexpected response from presentation service",
        detail: "No URL or generation ID returned"
      }),
      { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );

  } catch (error) {
    console.error("[generate-presentation] Unexpected error:", error);
    console.error("[generate-presentation] Error stack:", (error as Error).stack);
    return new Response(
      JSON.stringify({ 
        error: "An unexpected error occurred",
        detail: String(error)
      }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
