import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Upload, Eye, MessageSquare, Lock, ArrowRight, Shield } from 'lucide-react';
import { ROUTES } from '@/config/navigation';

export function FinalDecisionSection() {
  return (
    <section className="py-20 md:py-32 relative bg-[hsl(var(--surface-1))]">
      <div className="absolute inset-0 overflow-hidden"><div className="absolute top-0 left-1/4 w-96 h-96 rounded-full bg-[radial-gradient(circle,hsl(var(--primary)/0.08)_0%,transparent_70%)]" /><div className="absolute bottom-0 right-1/4 w-96 h-96 rounded-full bg-[radial-gradient(circle,hsl(var(--secondary)/0.05)_0%,transparent_70%)]" /></div>
      <div className="container px-4 relative z-10">
        <div className="max-w-3xl mx-auto text-center mb-8"><div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20 mb-6"><Shield className="w-4 h-4 text-primary" /><span className="text-sm font-medium text-primary">Choose Your Path</span></div><h2 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-6">Protect Yourself<span className="block mt-2 text-primary">Before You Sign Anything</span></h2><p className="text-lg text-muted-foreground">You've seen how the system works.<br />You've seen what most homeowners never do.<br /><span className="text-foreground font-medium">Now choose how you want to move forward — on your terms.</span></p></div>
        <div className="max-w-2xl mx-auto mb-16 text-center"><p className="text-muted-foreground">There's no countdown here. No obligation. No "right" answer.</p><p className="text-lg text-foreground font-medium mt-4">The only mistake is moving forward without clarity.</p><p className="text-muted-foreground mt-4">Whether you're ready to upload a quote, want to see exactly how the audit works, or just need a human to sanity-check what you're looking at — Window Man meets you where you are.</p></div>
        <div className="max-w-3xl mx-auto"><div className="grid gap-6">
          <div className="p-6 rounded-2xl bg-gradient-to-r from-primary/10 to-primary/5 border border-primary/30 hover:border-primary/50 transition-colors"><div className="flex flex-col md:flex-row items-center gap-6"><div className="flex-1 text-center md:text-left"><span className="text-xs font-medium text-primary uppercase tracking-wide">Best if you already have a quote</span><h3 className="text-xl font-bold text-foreground mt-1">Upload Your Estimate for a Free Audit</h3><p className="text-sm text-muted-foreground mt-2">You keep the report. No obligation.</p></div><Button asChild size="lg" variant="cta" className="group shrink-0"><Link to={ROUTES.QUOTE_SCANNER}><Upload className="mr-2 w-5 h-5" />Upload Now<ArrowRight className="ml-2 w-5 h-5 transition-transform group-hover:translate-x-1" /></Link></Button></div></div>
          <div className="p-6 rounded-2xl bg-card border border-border hover:border-primary/30 transition-colors"><div className="flex flex-col md:flex-row items-center gap-6"><div className="flex-1 text-center md:text-left"><span className="text-xs font-medium text-muted-foreground uppercase tracking-wide">No estimate required</span><h3 className="text-xl font-bold text-foreground mt-1">View a Full Sample AI Report (Free)</h3><p className="text-sm text-muted-foreground mt-2">See exactly what the audit looks like.</p></div><Button asChild size="lg" variant="outline" className="group shrink-0"><Link to="/sample-report"><Eye className="mr-2 w-5 h-5" />View Sample<ArrowRight className="ml-2 w-5 h-5 transition-transform group-hover:translate-x-1" /></Link></Button></div></div>
          <div className="p-6 rounded-2xl bg-card/50 border border-border/50 hover:border-border transition-colors"><div className="flex flex-col md:flex-row items-center gap-6"><div className="flex-1 text-center md:text-left"><span className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Need help deciding?</span><h3 className="text-lg font-semibold text-foreground mt-1">Talk to Window Man About My Quote</h3><p className="text-sm text-muted-foreground mt-2">If you want help deciding what to do next.</p></div><Button asChild variant="secondary" className="group shrink-0"><Link to={ROUTES.CONSULTATION}><MessageSquare className="mr-2 w-5 h-5" />Get Help</Link></Button></div></div>
          <div className="p-6 rounded-2xl bg-muted/30 border border-border/30 hover:border-border/50 transition-colors"><div className="flex flex-col md:flex-row items-center gap-6"><div className="flex-1 text-center md:text-left"><span className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Not ready yet?</span><h3 className="text-lg font-semibold text-foreground mt-1">Create a Free Window Vault</h3><p className="text-sm text-muted-foreground mt-2">Save your project, learn the risks, and come back when you're ready.</p></div><Button asChild variant="ghost" className="group shrink-0"><Link to={ROUTES.VAULT}><Lock className="mr-2 w-5 h-5" />Create Vault</Link></Button></div></div>
        </div></div>
        <div className="max-w-2xl mx-auto mt-16 text-center"><div className="p-8 rounded-2xl bg-gradient-to-br from-primary/5 via-transparent to-[hsl(var(--secondary)/0.05)] border border-border/50"><p className="text-muted-foreground mb-4">You don't need to rush. You don't need to switch contractors. You don't need to commit to anything.</p><p className="text-xl font-semibold text-foreground mb-4">You just need to stop negotiating blind.</p><p className="text-lg text-primary font-medium">Window Man gives you the leverage —<br /><span className="text-foreground">what you do with it is always your choice.</span></p></div></div>
      </div>
    </section>
  );
}
