import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { FileText, ArrowRight, MessageSquare, AlertTriangle, Shield, CheckCircle2, Eye, Upload, Scan, FileSearch } from 'lucide-react';
import { ROUTES } from '@/config/navigation';
export function SampleReportSection() {
  return <section className="py-20 md:py-32 relative bg-[hsl(var(--surface-1))]">
      <div className="container px-4">
        <div className="max-w-3xl mx-auto text-center mb-12"><h2 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-6">See the "Hidden Math" Your Contractor<span className="block mt-2 text-primary">Didn't Show You</span></h2><p className="text-lg text-muted-foreground">This isn't a generic score. It's a 40-point technical audit that turns a confusing five-page estimate into a clear, one-page strategy.</p></div>
        <div className="max-w-2xl mx-auto mb-16 text-center"><p className="text-lg text-muted-foreground">Most contractors show you a total.<br />They don't show you how that number was protected — or how it could be challenged.</p><p className="text-xl text-foreground font-semibold mt-4">This report does.</p></div>
        <div className="max-w-4xl mx-auto mb-16 shadow-none"><div className="p-8 md:p-10 rounded-2xl bg-card border border-border"><p className="text-lg text-muted-foreground mb-6">Most window quotes are designed to be just clear enough to get a signature — and just vague enough to hide risk.</p><p className="text-lg text-muted-foreground mb-4">Our AI audit scans every line item, every footnote, and every missing specification to give you what you actually need before signing:</p><p className="text-2xl font-bold text-primary text-center my-8">The truth — translated into leverage.</p><p className="text-lg text-muted-foreground text-center">When you look at your report, you're not just seeing a grade.<br /><span className="text-foreground font-medium">You're seeing a playbook.</span></p></div></div>
        <div className="max-w-4xl mx-auto mb-16"><h3 className="text-xl font-semibold text-foreground text-center mb-8">What You're Actually Holding</h3><div className="grid md:grid-cols-3 gap-6"><div className="p-6 rounded-xl bg-card border border-border hover:border-primary/30 transition-colors"><MessageSquare className="w-10 h-10 text-primary mb-4" /><h4 className="text-lg font-semibold text-foreground mb-2">The Exact Questions to Ask</h4><p className="text-sm text-muted-foreground">You're given the language to challenge missing permits, weak warranties, or vague scope — without sounding difficult or uninformed.</p></div><div className="p-6 rounded-xl bg-card border border-border hover:border-[hsl(var(--secondary)/0.3)] transition-colors"><AlertTriangle className="w-10 h-10 text-[hsl(var(--secondary))] mb-4" /><h4 className="text-lg font-semibold text-foreground mb-2">The Financial Red Flags</h4><p className="text-sm text-muted-foreground">The audit highlights where you're paying an ignorance tax compared to real local market rates.</p></div><div className="p-6 rounded-xl bg-card border border-border hover:border-green-500/30 transition-colors"><Shield className="w-10 h-10 text-green-500 mb-4" /><h4 className="text-lg font-semibold text-foreground mb-2">The Insurance Safeguard</h4><p className="text-sm text-muted-foreground">We verify critical technical codes — like Design Pressure — so you don't find out your windows are uninsurable after they're already installed.</p></div></div></div>
        <div className="max-w-5xl mx-auto mb-16"><h3 className="text-xl font-semibold text-foreground text-center mb-8">Same Document. Completely Different Understanding.</h3><div className="grid md:grid-cols-2 gap-6"><div className="p-6 rounded-xl bg-muted/30 border border-border"><div className="flex items-center gap-3 mb-4"><FileText className="w-6 h-6 text-muted-foreground" /><span className="text-sm font-medium text-muted-foreground uppercase tracking-wide">What You See</span></div><div className="space-y-3"><div className="h-4 bg-muted/50 rounded w-3/4" /><div className="h-4 bg-muted/50 rounded w-full" /><div className="h-4 bg-muted/50 rounded w-5/6" /><div className="h-8 bg-muted/50 rounded w-1/2 mt-6" /><p className="text-sm text-muted-foreground mt-4 italic">A total price. Technical jargon. Five pages of fine print.</p></div></div><div className="p-6 rounded-xl bg-gradient-to-br from-primary/10 to-[hsl(var(--secondary)/0.05)] border border-primary/30"><div className="flex items-center gap-3 mb-4"><Scan className="w-6 h-6 text-primary" /><span className="text-sm font-medium text-primary uppercase tracking-wide">What Window Man Sees</span></div><div className="space-y-3"><div className="flex items-center gap-2"><AlertTriangle className="w-4 h-4 text-red-500" /><span className="text-sm text-foreground">3 missing code requirements</span></div><div className="flex items-center gap-2"><AlertTriangle className="w-4 h-4 text-[hsl(var(--secondary))]" /><span className="text-sm text-foreground">15% price markup vs local market</span></div><div className="flex items-center gap-2"><AlertTriangle className="w-4 h-4 text-amber-500" /><span className="text-sm text-foreground">Hidden debris removal fee</span></div><p className="text-sm text-muted-foreground mt-4 italic">Actionable intelligence, not confusion.</p></div></div></div><p className="text-center text-muted-foreground mt-6">The difference isn't intelligence. <span className="text-foreground font-medium">It's visibility.</span></p></div>
        <div className="max-w-3xl mx-auto mb-12"><div className="p-8 rounded-2xl bg-gradient-to-r from-primary/10 via-transparent to-[hsl(var(--secondary)/0.1)] border border-primary/20 text-center"><h3 className="text-2xl font-bold text-foreground mb-4">Stop Hoping You Got a Good Deal.<span className="text-primary"> Start Knowing You Did.</span></h3><p className="text-muted-foreground mb-4">With this report in your hand, you don't walk back to a contractor asking for reassurance.</p><p className="text-lg text-foreground font-medium mb-6">You walk back with facts.</p><p className="text-muted-foreground">You become the most informed person at the table — the one setting the terms, not reacting to them.</p><div className="flex flex-col sm:flex-row items-center justify-center gap-4 mt-8"><div className="flex items-center gap-2 text-sm text-foreground"><CheckCircle2 className="w-4 h-4 text-green-500" />Keep your contractor and force the quote to improve</div><div className="flex items-center gap-2 text-sm text-foreground"><CheckCircle2 className="w-4 h-4 text-green-500" />Or let us find someone who already meets the standard</div></div><p className="text-lg text-[hsl(var(--secondary))] font-medium mt-6">Either way, the leverage is yours.</p></div></div>
        <div className="text-center space-y-4"><Button asChild size="lg" variant="cta" className="group"><Link to="/sample-report"><Eye className="mr-2 w-5 h-5" />View a Full Sample AI Report (Free)<ArrowRight className="ml-2 w-5 h-5 transition-transform group-hover:translate-x-1" /></Link></Button><p className="text-sm text-muted-foreground">See exactly how we stress-test a real quote. 100% free. No estimate required.</p><div className="pt-4"><Button asChild size="lg" variant="outline" className="group"><Link to={ROUTES.QUOTE_SCANNER}><Upload className="mr-2 w-5 h-5" />Upload Your Estimate for a Free Audit</Link></Button><p className="text-xs text-muted-foreground mt-2">No obligation. You keep the report.</p></div></div>
      </div>
    </section>;
}