import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { ArrowRight, MessageSquare, Zap, CheckCircle2, Shield, Upload } from 'lucide-react';
import { ROUTES } from '@/config/navigation';

export function WeaponizeAuditSection() {
  return (
    <section className="py-20 md:py-32 relative bg-gradient-to-b from-[hsl(28,30%,97.2%)] to-[hsl(210,24%,95.9%)] overflow-hidden isolate pattern-scanlines">
      {/* Ambient mesh blobs */}
      <div className="absolute top-0 left-0 w-80 h-80 rounded-full bg-[radial-gradient(circle,hsl(var(--secondary)/0.04)_0%,transparent_70%)] pointer-events-none" />
      <div className="absolute bottom-0 right-0 w-96 h-96 rounded-full bg-[radial-gradient(circle,hsl(var(--primary)/0.03)_0%,transparent_70%)] pointer-events-none" />
      <div className="container px-4">
        <div className="max-w-3xl mx-auto text-center mb-8"><h2 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-6">Once You Have the Report,<span className="block mt-2 text-primary">You're in Control</span></h2><p className="text-lg text-muted-foreground">It's a decision tool to choose how to win, not a file for a drawer.</p></div>
        <div className="max-w-2xl mx-auto mb-16 text-center"><p className="text-lg text-muted-foreground">Unlike most services, Window Man doesn't just hand you data and walk away. The audit gives you two clear paths to win, ensuring you are never negotiating blind.</p></div>
        <div className="max-w-5xl mx-auto mb-16"><div className="grid md:grid-cols-2 gap-8">
          <div className="relative p-8 rounded-2xl bg-card border border-primary/30 hover:border-primary/50 transition-colors"><div className="absolute -top-4 left-8 px-4 py-1 bg-primary text-primary-foreground text-sm font-semibold rounded-full">Path A</div><div className="flex items-center gap-3 mt-4 mb-6"><div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center"><MessageSquare className="w-6 h-6 text-primary" /></div><div><h3 className="text-xl font-bold text-foreground">The Negotiator</h3><p className="text-sm text-primary font-medium">"Keep Your Contractor, Fix Your Contract."</p></div></div><div className="space-y-6"><div><h4 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide mb-2">The Strategy</h4><p className="text-muted-foreground">If you like your current contractor but the AI flagged risks in their quote, use the report as your expert script.</p></div><div><h4 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide mb-2">How it Works</h4><p className="text-muted-foreground">We give you the exact technical questions to ask about missing permits, weak warranties, or "Scope Gaps."</p></div><div className="p-4 rounded-xl bg-primary/5 border border-primary/20"><h4 className="text-sm font-semibold text-foreground mb-2 flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-primary" />The Outcome</h4><p className="text-sm text-muted-foreground">You force them to match the high standards the AI identified as missing. You sign a "bulletproof" contract with the contractor you already trust, knowing you aren't leaving $5,000 of protection on the table.</p></div></div></div>
          <div className="relative p-8 rounded-2xl bg-card border border-[hsl(var(--secondary)/0.3)] hover:border-[hsl(var(--secondary)/0.5)] transition-colors"><div className="absolute -top-4 left-8 px-4 py-1 bg-[hsl(var(--secondary))] text-white text-sm font-semibold rounded-full">Path B</div><div className="flex items-center gap-3 mt-4 mb-6"><div className="w-12 h-12 rounded-xl bg-[hsl(var(--secondary)/0.1)] flex items-center justify-center"><Zap className="w-6 h-6 text-[hsl(var(--secondary))]" /></div><div><h3 className="text-xl font-bold text-foreground">The Disrupter</h3><p className="text-sm text-[hsl(var(--secondary))] font-medium">"Let the Market Compete for Your Business."</p></div></div><div className="space-y-6"><div><h4 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide mb-2">The Strategy</h4><p className="text-muted-foreground">If you aren't married to your contractor — or if they refuse to fix the risks we found — flip the switch.</p></div><div><h4 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide mb-2">How it Works</h4><p className="text-muted-foreground">With one click, you authorize Window Man to share your project specifications (never your personal data) with our vetted partner network.</p></div><div className="p-4 rounded-xl bg-[hsl(var(--secondary)/0.05)] border border-[hsl(var(--secondary)/0.2)]"><h4 className="text-sm font-semibold text-foreground mb-2 flex items-center gap-2"><Shield className="w-4 h-4 text-[hsl(var(--secondary))]" />The Promise</h4><p className="text-sm text-muted-foreground">We force top-tier pros to compete for your job. Our goal is simple: find a partner who will do the same job, with the same materials and better warranties, for a lower price.</p></div></div></div>
        </div></div>
        <div className="max-w-3xl mx-auto mb-12"><div className="p-8 md:p-10 rounded-2xl bg-gradient-to-br from-primary/5 via-card to-[hsl(var(--secondary)/0.05)] border border-border"><h3 className="text-xl font-bold text-foreground text-center mb-6">The "Checkmate" Position</h3><p className="text-lg text-muted-foreground text-center mb-4">Either way, the industry gets more honest, and you get a better deal.</p><p className="text-muted-foreground text-center mb-6">Window Man doesn't care which path you take. Our only loyalty is to the audit.</p><p className="text-lg text-foreground font-medium text-center">Whether you use our data to fix a bad quote or use our network to find a better one, you are no longer the "uninformed homeowner."</p><p className="text-xl text-primary font-bold text-center mt-4">You are the most prepared person at the table.</p></div></div>
        <div className="text-center"><Button asChild size="lg" variant="cta" className="group"><Link to={ROUTES.QUOTE_SCANNER}><Upload className="mr-2 w-5 h-5" />Get the Leverage You Need. Upload Your Estimate<ArrowRight className="ml-2 w-5 h-5 transition-transform group-hover:translate-x-1" /></Link></Button><p className="mt-3 text-sm text-muted-foreground">100% Free. No obligation to use our partners.</p></div>
      </div>
    </section>
  );
}
