// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's id and email. Use to verify the MCP connection.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = { userId: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-quote-analyses.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_quote_analyses_default = defineTool2({
  name: "list_my_quote_analyses",
  title: "List my quote analyses",
  description: "List window-quote analyses that belong to the signed-in user's account. Returns id, created_at, overall_score, price_per_opening, and warning counts.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = supabaseForUser(ctx);
    const { data: account, error: accountError } = await client.from("accounts").select("id").eq("supabase_user_id", ctx.getUserId()).maybeSingle();
    if (accountError) {
      return { content: [{ type: "text", text: accountError.message }], isError: true };
    }
    if (!account) {
      return {
        content: [{ type: "text", text: "No account found for this user." }],
        structuredContent: { rows: [] }
      };
    }
    const { data, error } = await client.from("quote_analyses").select(
      "id, created_at, overall_score, safety_score, price_score, warranty_score, price_per_opening, warnings_count, missing_items_count"
    ).eq("account_id", account.id).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-quote-analysis.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_quote_analysis_default = defineTool3({
  name: "get_quote_analysis",
  title: "Get quote analysis",
  description: "Return the full analysis for a single quote (scores, warnings, findings) owned by the signed-in user.",
  inputSchema: {
    id: z2.string().uuid().describe("Quote analysis id (uuid).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("quote_analyses").select(
      "id, created_at, overall_score, safety_score, scope_score, price_score, fine_print_score, warranty_score, price_per_opening, warnings_count, missing_items_count, analysis_json"
    ).eq("id", id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kffoximblqwcnznwvugu";
var mcp_default = defineMcp({
  name: "window-man-mcp",
  title: "Window Man MCP",
  version: "0.1.0",
  instructions: "Tools for the Window Man Truth Engine. Use `whoami` to verify connectivity, `list_my_quote_analyses` to list a user's window-quote analyses, and `get_quote_analysis` to fetch one by id.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_quote_analyses_default, get_quote_analysis_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
